os:
  - linux
  - osx

include:
  jobs:
    -
      name: "Ubuntu 16.04"
      os: linux
      dist: xenial  # Ubuntu 16.04
    -
      name: "Ubuntu 18.04"
      os: linux
      dist: bionic  # Ubuntu 18.04
    -
      name: "Ubuntu 20.04"
      os: linux
      dist: focal  # Ubuntu 20.04  
    -
      name: "Monterey"
      os: osx
      osx_image: xcode13.2  # Monterey
    -
      name: "Big Sur"
      os: osx
      osx_image: xcode13.1  # Big Sur
    -
      name: "Catalina"
      os: osx
      osx_image: xcode12.2  # Catalina, last version still supported

git:
  depth: false

language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10

before_install:
  - pip install -U pip
  - pip install -U pytest

# We add python path to enable testing jupyter notebooks
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-test.txt
  - travis_retry export PYTHONPATH=$PWD

env:
  - MPLBACKEND=Agg

cache: pip

# command to run tests
script:
  - python -m pytest --cov=ark --pycodestyle ark

jobs:
  include:
    - stage: deploy
      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        on:
          tags: true

after_success:
  - coveralls
